export const GET_CONVERSATIONS_REQUEST = 'GET_CONVERSATIONS_REQUEST'
export const GET_CONVERSATIONS_SUCCESS = 'GET_CONVERSATIONS_SUCCESS'
export const GET_CONVERSATIONS_FAIL = 'GET_CONVERSATIONS_FAIL'

export const CREATE_CONVERSATION_REQUEST = 'CREATE_CONVERSATION_REQUEST'
export const CREATE_CONVERSATION_SUCCESS = 'CREATE_CONVERSATION_SUCCESS'
export const CREATE_CONVERSATION_FAIL = 'CREATE_CONVERSATION_FAIL'

export const UPDATE_CONVERSATION_REQUEST = 'UPDATE_CONVERSATION_REQUEST'
export const UPDATE_CONVERSATION_SUCCESS = 'UPDATE_CONVERSATION_SUCCESS'
export const UPDATE_CONVERSATION_FAIL = 'UPDATE_CONVERSATION_FAIL'

export const DELETE_CONVERSATION_REQUEST = 'DELETE_CONVERSATION_REQUEST'
export const DELETE_CONVERSATION_SUCCESS = 'DELETE_CONVERSATION_SUCCESS'
export const DELETE_CONVERSATION_FAIL = 'DELETE_CONVERSATION_FAIL'



export const ADD_NEWCONVERSATION = 'ADD_NEWCONVERSATION'