export const GET_MESSAGES_REQUEST='GET_MESSAGES_REQUEST'
export const GET_MESSAGES_SUCCESS='GET_MESSAGES_SUCCESS'
export const GET_MESSAGES_FAIL='GET_MESSAGES_FAIL'

export const CREATE_MESSAGE_REQUEST='CREATE_MESSAGE_REQUEST'
export const CREATE_MESSAGE_SUCCESS='CREATE_MESSAGE_SUCCESS'
export const CREATE_MESSAGE_FAIL='CREATE_MESSAGE_FAIL'

export const DELETE_MESSAGE_REQUEST='DELETE_MESSAGE_REQUEST'
export const DELETE_MESSAGE_SUCCESS='DELETE_MESSAGE_SUCCESS'
export const DELETE_MESSAGE_FAIL='DELETE_MESSAGE_FAIL'