export const GET_USERLIST_REQUEST ='GET_USERLIST_REQUEST'
export const GET_USERLIST_SUCCESS ='GET_USERLIST_SUCCESS'
export const GET_USERLIST_FAIL ='GET_USERLIST_FAIL'

export const GET_USER_REQUEST ='GET_USER_REQUEST'
export const GET_USER_SUCCESS ='GET_USER_SUCCESS'
export const GET_USER_FAIL ='GET_USER_FAIL'

export const EDIT_USER_REQUEST ='EDIT_USER_REQUEST'
export const EDIT_USER_SUCCESS ='EDIT_USER_SUCCESS'
export const EDIT_USER_FAIL ='EDIT_USER_FAIL'

export const ADD_USER_TEAM_REQUEST ='ADD_USER_TEAM_REQUEST'
export const ADD_USER_TEAM_SUCCESS ='ADD_USER_TEAM_SUCCESS'
export const ADD_USER_TEAM_FAIL ='ADD_USER_TEAM_FAIL'

export const DELETE_USER_TEAM_REQUEST ='DELETE_USER_TEAM_REQUEST'
export const DELETE_USER_TEAM_SUCCESS ='DELETE_USER_TEAM_SUCCESS'
export const DELETE_USER_TEAM_FAIL ='DELETE_USER_TEAM_FAIL'