export const GET_COMPANYLIST_REQUEST = 'GET_COMPANYLIST_REQUEST'
export const GET_COMPANYLIST_SUCCESS = 'GET_COMPANYLIST_SUCCESS'
export const GET_COMPANYLIST_FAIL = 'GET_COMPANYLIST_FAIL'

export const GET_COMPANY_REQUEST = 'GET_COMPANY_REQUEST'
export const GET_COMPANY_SUCCESS = 'GET_COMPANY_SUCCESS'
export const GET_COMPANY_FAIL = 'GET_COMPANY_FAIL'