export const GET_COMPANYLIST_REQUEST = 'GET_COMPANYLIST_REQUEST'
export const GET_COMPANYLIST_SUCCESS = 'GET_COMPANYLIST_SUCCESS'
export const GET_COMPANYLIST_FAIL = 'GET_COMPANYLIST_FAIL'


export const GET_COMPANY_REQUEST = 'GET_COMPANY_REQUEST'
export const GET_COMPANY_SUCCESS = 'GET_COMPANY_SUCCESS'
export const GET_COMPANY_FAIL = 'GET_COMPANY_FAIL'

export const CREATE_COMPANY_REQUEST = 'CREATE_COMPANY_REQUEST'
export const CREATE_COMPANY_SUCCESS = 'CREATE_COMPANY_SUCCESS'
export const CREATE_COMPANY_FAIL = 'CREATE_COMPANY_FAIL'

export const EDIT_COMPANY_REQUEST = 'EDIT_COMPANY_REQUEST'
export const EDIT_COMPANY_SUCCESS = 'EDIT_COMPANY_SUCCESS'
export const EDIT_COMPANY_FAIL = 'EDIT_COMPANY_FAIL'

export const DELETE_COMPANY_REQUEST = 'DELETE_COMPANY_REQUEST'
export const DELETE_COMPANY_SUCCESS = 'DELETE_COMPANY_SUCCESS'
export const DELETE_COMPANY_FAIL = 'DELETE_COMPANY_FAIL'

export const GET_COMPANIES_REQUEST = 'GET_COMPANIES_REQUEST'
export const GET_COMPANIES_SUCCESS = 'GET_COMPANIES_SUCCESS'
export const GET_COMPANIES_FAIL = 'GET_COMPANIES_FAIL'

export const GET_ALL_COMPANIES_REQUEST = 'GET_ALL_COMPANIES_REQUEST'
export const GET_ALL_COMPANIES_SUCCESS = 'GET_ALL_COMPANIES_SUCCESS'
export const GET_ALL_COMPANIES_FAIL = 'GET_ALL_COMPANIES_FAIL'

export const GET_COMPANIES_RECOMMENDATION_REQUEST = 'GET_COMPANIES_RECOMMENDATION_REQUEST'
export const GET_COMPANIES_RECOMMENDATION_SUCCESS = 'GET_COMPANIES_RECOMMENDATION_SUCCESS'
export const GET_COMPANIES_RECOMMENDATION_FAIL = 'GET_COMPANIES_RECOMMENDATION_FAIL'

export const GET_COMPANIES_SEARCH_REQUEST = 'GET_COMPANIES_SEARCH_REQUEST'
export const GET_COMPANIES_SEARCH_SUCCESS = 'GET_COMPANIES_SEARCH_SUCCESS'
export const GET_COMPANIES_SEARCH_FAIL = 'GET_COMPANIES_SEARCH_FAIL'

export const GET_LOAD_MORE_COMPANIES='GET_LOAD_MORE_COMPANIES'