export const GET_TEAMLIST_REQUEST = 'GET_TEAMLIST_REQUEST'
export const GET_TEAMLIST_SUCCESS = 'GET_TEAMLIST_SUCCESS'
export const GET_TEAMLIST_FAIL = 'GET_TEAMLIST_FAIL'

export const GET_TEAM_REQUEST = 'GET_TEAM_REQUEST'
export const GET_TEAM_SUCCESS = 'GET_TEAM_SUCCESS'
export const GET_TEAM_FAIL = 'GET_TEAM_FAIL'

export const GET_TEAMS_REQUEST = 'GET_TEAMS_REQUEST'
export const GET_TEAMS_SUCCESS = 'GET_TEAMS_SUCCESS'
export const GET_TEAMS_FAIL = 'GET_TEAMS_FAIL'

